// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_shop.Models;

namespace e_shop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210422120103_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_shop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fruit Sweets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gummy Sweets"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Halloween Sweets"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hard Boiled Sweets"
                        });
                });

            modelBuilder.Entity("e_shop.Models.Sweet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbNailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Sweets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\chocolateSweets-small.jpg",
                            ImageUrl = "~\\images\\chocolateSweets.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Chocolate",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\chocolateSweets2-small.jpg",
                            ImageUrl = "~\\images\\chocolateSweets2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Chocolate 2",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\chocolateSweets3-small.jpg",
                            ImageUrl = "~\\images\\chocolateSweets3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Chocolate 3",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\fruitSweets-small.jpg",
                            ImageUrl = "~\\images\\fruitSweets.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Fruit Sweets",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\fruitSweets2-small.jpg",
                            ImageUrl = "~\\images\\fruitSweets2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Fruit Sweets 2",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\fruitSweets3-small.jpg",
                            ImageUrl = "~\\images\\fruitSweets3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Fruit Sweets 3",
                            Price = 1.49m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\gummySweets-small.jpg",
                            ImageUrl = "~\\images\\gummySweets.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Gummy Sweets 2",
                            Price = 0.59m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\gummySweets2-small.jpg",
                            ImageUrl = "~\\images\\gummySweets2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Gummy Sweets",
                            Price = 1.49m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\gummySweets3-small.jpg",
                            ImageUrl = "~\\images\\gummySweets3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Gummy Sweets 3",
                            Price = 6.19m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\halloweenSweets-small.jpg",
                            ImageUrl = "~\\images\\halloweenSweets.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Halloween Sweets",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\halloweenSweets2-small.jpg",
                            ImageUrl = "~\\images\\halloweenSweets2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Halloween Sweets 2",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\halloweenSweets3-small.jpg",
                            ImageUrl = "~\\images\\halloweenSweets3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Halloween Sweets 3",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\hardSweets-small.jpg",
                            ImageUrl = "~\\images\\hardSweets.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Hard Boiled Sweet",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\hardSweets2-small.jpg",
                            ImageUrl = "~\\images\\hardSweets2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Hard Boiled Sweets 2",
                            Price = 3.19m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageThumbNailUrl = "~\\images\\thumbnails\\hardSweets3-small.jpg",
                            ImageUrl = "~\\images\\hardSweets3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Hard Boiled Sweets 3",
                            Price = 0.99m
                        });
                });

            modelBuilder.Entity("e_shop.Models.Sweet", b =>
                {
                    b.HasOne("e_shop.Models.Category", "Category")
                        .WithMany("Sweets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("e_shop.Models.Category", b =>
                {
                    b.Navigation("Sweets");
                });
#pragma warning restore 612, 618
        }
    }
}
